main: com.gmail.woodyc40.nameplate.Nameplate
name: Nameplate
version: ${project.version}
api-version: "1.14"
depend: [ ProtocolLib ]

commands:
  nameplate:
    description: Sets your nameplate to a different string or removes the custom nameplate
    usage: /nameplate [name]
